// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gezimesyodtrdtdlplas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlemltZXN5b2R0cmR0ZGxwbGFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MjYxMzIsImV4cCI6MjA2ODMwMjEzMn0.DTvDc8AsfiikidmE0y4XQy43e0LwVEA8sLKiAGS4F4Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});