// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://elzzyqamcuqheykafauc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVsenp5cWFtY3VxaGV5a2FmYXVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMzczNTQsImV4cCI6MjA2NjkxMzM1NH0.WGTjhApsD31jFNE41o4FlBw6KOT1gre-rx_0IrxXVuc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});